#pragma once
#include "CoreMinimal.h"
#include "ORBaseGarmantuousPart2Character_StunDamageThresholdReachedDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FORBaseGarmantuousPart2Character_StunDamageThresholdReached);

